version: "3.7"
services:
  molo:
    build:
      context: ./
      dockerfile: molo/Dockerfile
    ports:
      - 8003:8003
    depends_on:
      - "frontend"
  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
    - 80:80
    environment:
      - BASE_URL=${BASE_URL}
    command: ["nginx", "-g", "daemon off;"]
