version: "3.7"
services:
  molo:
    build:
      context: ./
      dockerfile: molo/Dockerfile
    ports:
      - "localhost:8003":"8003"
    env_file:
      - ./.env
    depends_on:
      - "frontend"
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
    - 80:80
    env_file:
      - ./.env
    command: ["nginx", "-g", "daemon off;"]
