version: "3.7"
services:
  molo:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - "frontend"
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
    - 80:80
    command: ["nginx", "-g", "daemon off;"]
